<?php
/** @package Gera::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ArtigoMap.php");

/**
 * ArtigoDAO provides object-oriented access to the artigo table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Gera::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ArtigoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var string */
	public $CaminhoArtigo;

	/** @var int */
	public $Evento;

	/** @var int */
	public $Autor;


	/**
	 * Returns a dataset of Nota objects with matching Artigo
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetNotas($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "nota_ibfk_1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Evento
	 * @return Evento
	 */
	public function GetEvento()
	{
		return $this->_phreezer->GetManyToOne($this, "artigo_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of Autor
	 * @return Usuario
	 */
	public function GetAutorUsuario()
	{
		return $this->_phreezer->GetManyToOne($this, "artigo_ibfk_2");
	}


}
?>