<?php
/** @package Gera::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EventoMap.php");

/**
 * EventoDAO provides object-oriented access to the evento table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Gera::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EventoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var date */
	public $DataInicio;

	/** @var date */
	public $DataFim;

	/** @var int */
	public $MaximoArtigos;


	/**
	 * Returns a dataset of Artigo objects with matching Evento
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetArtigos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "artigo_ibfk_1", $criteria);
	}


}
?>