<?php
/** @package Gera::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("UsuarioMap.php");

/**
 * UsuarioDAO provides object-oriented access to the usuario table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Gera::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class UsuarioDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Email;

	/** @var string */
	public $Senha;

	/** @var string */
	public $Tipo;


	/**
	 * Returns a dataset of Artigo objects with matching Autor
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAutorArtigos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "artigo_ibfk_2", $criteria);
	}

	/**
	 * Returns a dataset of Nota objects with matching Avaliador
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAvaliadorNotas($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "nota_ibfk_2", $criteria);
	}


}
?>